services:
  - type: web
    name: Backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
